Firebase projectsetup backendserver
inlearna-dev-demo/Inlearna-backend pull request #1
Opened 2024-12-02 18:01 UTC by anujdeol

project setup: firebase, mongodb connection

2024-12-02 18:35 UTC, inleanadev requested changes
Hi Anuj, Could you please ensure that Firebase credentials are not hardcoded in the code? Instead, could you store them in environment variables for better security and easier management across different environments?

2024-12-02 18:35 UTC, inleanadev commented on functions/accountServiceKey.json
Hi Anuj, could you please ensure that Firebase credentials are not hardcoded in the code? Instead, could you store them in environment variables for better security and easier management across different environments?

2024-12-02 18:42 UTC, anujdeol commented on functions/accountServiceKey.json
Hi, since we are not yet sure which admin sdk we'll be using for the common repo deployment, once the other teammates have successfully set up their backend environment, I will transfer all the sensitive environment variables to Firebase's environment variable management system.

2024-12-02 18:45 UTC, inleanadev commented on functions/accountServiceKey.json
Perfect sounds good!

2024-12-02 21:33 UTC, inleanadev approved these changes

2024-12-02 22:09 UTC, qingqw77 approved these changes

2024-12-03 13:56 UTC, inleanadev approved these changes

2024-12-04 16:17 UTC, qingqingw77 approved these changes

2024-12-04 16:24 UTC, merged